// Catalog copied into each new class. After a class exists, edit its catalog on the instructor page, not here.

// [code, name, link, own choice, reserved]
export const SEED_DATASETS = [
  [0,"Hospital readmission prediction dataset","https://www.kaggle.com/datasets/abhaypanchal/hospital-readmission-prediction-dataset","no","Instructor example"],
  [1,"Diabetes","https://www.kaggle.com/datasets/uciml/pima-indians-diabetes-database","no",""],
  [2,"Heart 1","https://www.kaggle.com/datasets/andrewmvd/heart-failure-clinical-data","no",""],
  [3,"Heart 2","https://www.kaggle.com/datasets/fedesoriano/heart-failure-prediction","no",""],
  [4,"Maternal health risk data","https://www.kaggle.com/datasets/csafrit2/maternal-health-risk-data","no",""],
  [5,"Body fat","https://www.kaggle.com/datasets/fedesoriano/body-fat-prediction-dataset","no",""],
  [6,"World happiness report 2021","https://www.kaggle.com/datasets/ajaypalsinghlo/world-happiness-report-2021","no",""],
  [7,"Stroke","https://www.kaggle.com/datasets/fedesoriano/stroke-prediction-dataset","no",""],
  [8,"Heart attack risk prediction dataset","https://www.kaggle.com/datasets/iamsouravbanerjee/heart-attack-prediction-dataset","no",""],
  [9,"Lung cancer","https://www.kaggle.com/datasets/nancyalaswad90/lung-cancer","no",""],
  [10,"Healthcare fraud detection dataset","https://www.kaggle.com/datasets/nudratabbas/healthcare-fraud-detection-dataset","no",""],
  [11,"Early wake-up, exercise & health outcomes dataset","https://www.kaggle.com/datasets/aliyasaly1231/early-wake-up-exercise-and-health-outcomes-dataset","no",""],
  [12,"Healthy diet & calorie intake nutrition & health","https://www.kaggle.com/datasets/aliyasaly1231/healthy-diet-and-calorie-intake","no",""],
  [13,"Mental health prediction dataset","https://www.kaggle.com/datasets/harpartapsingh13/mental-health-prediction-dataset","no",""],
  [14,"Diabetes prediction dataset","https://www.kaggle.com/datasets/iammustafatz/diabetes-prediction-dataset","no",""],
  [15,"Healthcare patient analytics dataset","https://www.kaggle.com/datasets/abbas829/healthcare-patient-analytics-dataset","no",""],
  [16,"Lifestyle & stress level prediction dataset","https://www.kaggle.com/datasets/shubhamdecode/lifestyle-and-stress-level-prediction-dataset","no",""],
  [17,"Student burnout prediction dataset","https://www.kaggle.com/datasets/danieljhuang/student-burnout-prediction-dataset","no",""],
  [18,"A dataset of your choosing from Kaggle (at least 50 upvotes, related to health economics and policy)","https://www.kaggle.com/datasets","yes",""]
];

// [code, topic, description]
export const SEED_TOPICS = [
  [1,"The price of insulin","Briefly explain what insulin is and why it is essential for millions of Americans. Then explain the pricing trend: what did insulin cost in the early 2000s, and what does it cost now? Identify the main companies that manufacture insulin in the US and discuss why competition among them did not bring prices down. Mention the role of pharmacy benefit managers and rebates in the pricing chain. End with any recent policy efforts to cap insulin prices."],
  [2,"Oregon Medicaid eligibility expansion by lottery","Explain what Medicaid is and who it covers. Describe the Oregon Health Insurance Experiment: why did Oregon use a lottery, how many people applied versus how many won, and what did researchers study? Summarize the key findings on healthcare utilization, financial protection, and health outcomes. Discuss why this study is considered one of the most important natural experiments in health economics."],
  [3,"340B Drug Pricing Program","Explain what the 340B program is, when it was created, and its original purpose. Then discuss: how has the program expanded beyond its original scope? Are the savings actually reaching patients, or are hospitals and pharmacies capturing the profits? Mention how large the program has become in dollar terms."],
  [4,"Expensive ER visits in the US","Compare the cost of an ER visit in the us versus other countries. Discuss the factors that drive this. Discuss whether this is a pricing problem, a utilization problem, or something else."],
  [5,"Surprise billing","Explain the concept of surprise billing. Give a sense of how common this was and the typical dollar amounts involved. Then explain what the No Surprises Act does, how does it protect patients, and how does the arbitration process between insurers and providers work? Mention any early evidence on whether the law is working as intended."],
  [6,"Drug reimportation","Explain what drug reimportation means. Present the arguments in favor and against it. Discuss whether any states have actually tried to implement importation programs and what happened."],
  [7,"Upcoding in Medicare","Define upcoding. Explain why the structure of Medicare reimbursement creates an incentive to upcode. Give examples. Discuss estimates of how much upcoding costs Medicare annually. Mention what the government has done to detect and penalize it, and how effective those efforts have been."],
  [8,"Martin Shkreli's Daraprim price hike","Explain what Daraprim is, what it treats, and how long it had been on the market at a low price. Describe what Shkreli did: acquiring the drug and raising the price from $13.50 to $750 per pill overnight. Explain why this was legally possible. Discuss the public and political backlash, what actually happened to the price afterward, and what this case reveals about the limits of market forces in pharmaceutical pricing."],
  [9,"Reference pricing in Germany","Explain what reference pricing means. Describe how Germany implemented this system and what the effects were on drug spending, generic uptake, and pharmaceutical company behavior. Discuss whether this approach could work in the U.S. and what obstacles would stand in the way."],
  [10,"EpiPens sell for $600 in the US and under $100 in other developed countries","Explain what an EpiPen is, who needs it, and why it is a life-or-death product. Trace the pricing history: what did it cost initially? How about a decade ago? How about now? Explain why an auto-injector of a cheap generic drug (epinephrine) can carry such a markup. Mention the role of patents on the delivery device rather than the drug itself. Discuss any alternatives that have since entered the market."],
  [11,"Medical bills and medical bankruptcy","Describe the scale of the problem: how many Americans carry medical debt, and what are the typical amounts? Walk through what actually happens when a patient cannot pay. Mention any recent policy changes, such as states limiting medical debt collection or removing medical debt from credit reports."],
  [12,"Medical debt and credit score","In what ways is medical debt unique and involuntary? Describe how medical bills enter the collections process and appear on credit reports. Discuss the scale. Explain recent changes (regulations, credit bureau policy changes, etc.). Discuss whether these changes go far enough."],
  [13,"Prior authorization","Define prior authorization. What was the rationale for imposing prior authorization? Then present the criticism from physicians and patients. Give statistics on the volume of prior authorization requests and denial rates. Mention any recent state or federal efforts to reform the process."],
  [14,"Tylenol: pennies at a pharmacy, $30 in hospitals","Explain the concept of hospital chargemasters. Explain how hospitals justify it. How do these markups disproportionately affect uninsured and out-of-network patients?"],
  [15,"Step therapy","Define step therapy. Explain the insurer's rationale for creating it. Then present the criticisms. Give specific anecdotal examples. Discuss any state laws that have been passed to reform step therapy requirements."],
  [16,"Uninsured patients often pay more than insured patients","Explain how insurance companies negotiate discounted rates with providers, and how the \"list price\" or chargemaster price is what uninsured patients are billed. Give a concrete example of the price difference for a common procedure. Discuss why this is considered paradoxical. Mention recent legal and legislative efforts to protect uninsured patients from inflated charges, including hospital financial assistance policies."],
  [17,"The history of insulin","Start with the discovery: who invented insulin, when, and the famous decision to sell the patent for $1. Explain how the product evolved: from animal-derived insulin to synthetic analogs. Discuss how each new formulation received its own patent, effectively restarting the patent clock. Identify the three companies that dominate the global insulin market and discuss why generic competitors have struggled to enter. Mention the concept of \"biologic\" vs. \"small molecule\" drugs and how it complicates generic entry for insulin specifically."],
  [18,"Johnson & Johnson baby powder controversy","Explain the product and its widespread household use. Summarize the investigative findings: internal documents showing that J&J knew about asbestos contamination as early as the 1970s. Describe the legal consequences: the volume of lawsuits, the jury verdicts, and J&J's controversial use of the \"Texas Two-Step\" bankruptcy maneuver to limit its liability. Discuss what this case reveals about corporate incentives when the expected profit from continued sales exceeds the expected cost of future lawsuits."],
  [19,"Medical tourism","Define medical tourism and explain why it exists. Identify the most common destinations. Give examples of the price differences for common procedures: dental work, hip replacement, cosmetic surgery. Are there any risks, criticisms, or downsides? Why do many US employers subsidize and facilitate medical tourism?"],
  [20,"Mark Cuban's Cost Plus Pharmacy","Explain how drug pricing normally works. Then explain the Cost Plus model: manufacturer cost plus a flat 15% markup plus a small pharmacy fee. Give examples of specific drugs and the price difference. Discuss the limitations. Evaluate whether this model can scale or whether it will remain a niche alternative."],
  [21,"The Inflation Reduction Act","Explain the idea of the Inflation Reduction Act and its attempt to bring down drug prices. Identify the first batch of drugs selected for negotiation and the conditions they treat. Find some numbers to report whether it has been successful. Discuss the pharmaceutical industry's response, including lawsuits. Does negotiating on ten drugs meaningfully change the landscape?"],
  [22,"Mandatory hospital price transparency","Starting in 2021, hospitals must publish their negotiated rates. What fraction of hospitals are actually complying, and what are the penalties for noncompliance? Explain why, even when prices are posted, most patients find the data unusable. Discuss whether any studies have found evidence that the rule has affected prices or patient behavior."],
  [23,"Should public insurance pay for GLP-1 weight-loss drugs?","Explain what GLP-1 drugs are, how they work, and why demand has surged. How much does a month of utilization cost? Discuss the potential benefits and concern. If insurance plans cover it, it is estimated to cost the Medicare over a trillion dollars. Discuss whether the Medicare should cover it."],
  [24,"The 988 Suicide and Crisis Lifeline","Explain the old system, the 10-digit National Suicide Prevention Lifeline number and its limitations. Describe the transition to 988. Present the data: call volumes before and after the switch, answer rates, and wait times. Discuss the funding challenge. Is there any study about the benefits and costs of transitioning to 988?"],
  [25,"Maternal mortality in the US","Find and compare the maternal mortality statistics of the U.S. versus other developed countries. Discuss the reasons. Discuss the policies implemented to address it and whether they have achieved meaningful improvement."]
];
